version: '3.8'

services:
  # Main application
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password@mongo:27017/tunnel-saas?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-here
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-here
      - BASE_DOMAIN=tunnel.suadominio.io
      - ADMIN_DOMAIN=admin.suadominio.io
    depends_on:
      - mongo
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - tunnel-network

  # MongoDB database
  mongo:
    image: mongo:5
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=tunnel-saas
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - tunnel-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - tunnel-network

  # Client (React app)
  client:
    build: ./client
    ports:
      - "3002:80"
    environment:
      - REACT_APP_SERVER_URL=http://app:3000
      - REACT_APP_BASE_DOMAIN=tunnel.suadominio.io
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - tunnel-network

volumes:
  mongo_data:
  redis_data:

networks:
  tunnel-network:
    driver: bridge
